[build]
  publish = "dist"
  command = "npm run build"

[[headers]]
  for = "/favicon.ico"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/logo192.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/logo512.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/manifest.json"
  [headers.values]
    Cache-Control = "public, max-age=31536000" 